/-
  StochasticSOS — Stochastic Extension of the Sacred Object System

  Extends the deterministic SOS framework to stochastic settings.
  The deterministic update operator δ : P → P is replaced by a
  Markov kernel κ : Kernel P P, and convergence follows from
  Doob's submartingale convergence theorem via the Ionescu-Tulcea
  construction (Mathlib.Probability.Kernel.IonescuTulcea.Traj).

  Key results:
  - StochasticSOS structure with Markov kernel transition
  - Almost-sure convergence of evaluator sequence (Doob's theorem)
  - Embedding functor SOS ↪ StochasticSOS via Kernel.deterministic
-/

import Mathlib.Probability.Kernel.IonescuTulcea.Traj
import Mathlib.Probability.Martingale.Convergence
import SosFormalization.Basic

open MeasureTheory ProbabilityTheory Filter Topology Preorder
open scoped ENNReal NNReal MeasureTheory

noncomputable section

/-! ## Homogeneous Kernel Specialization

The Ionescu-Tulcea module handles inhomogeneous kernels
`κ : (n : ℕ) → Kernel (∀ i : Iic n, X i) (X (n + 1))`
with potentially different spaces at each time step.
We specialize to the homogeneous case: constant space P and constant kernel. -/

variable {P : Type*} [MeasurableSpace P]

/-- Wrap a time-homogeneous Markov kernel κ : Kernel P P into the
    inhomogeneous Ionescu-Tulcea API. At time n, extracts the current
    state (coordinate n) from the trajectory and applies κ. -/
def homKernel (κ : Kernel P P) (n : ℕ) :
    Kernel ((i : ↥(Finset.Iic n)) → P) P :=
  κ.comap (fun x => x ⟨n, Finset.mem_Iic.mpr le_rfl⟩) (measurable_pi_apply _)

instance homKernel.instIsMarkovKernel (κ : Kernel P P) [IsMarkovKernel κ] (n : ℕ) :
    IsMarkovKernel (homKernel κ n) := by
  unfold homKernel; infer_instance

/-- Path measure for the coordinate process on ℕ → P, constructed via
    Ionescu-Tulcea from a deterministic initial condition π₀. -/
def sosPathMeasure (π₀ : P) (κ : Kernel P P) [IsMarkovKernel κ] :
    Measure (ℕ → P) :=
  Kernel.trajMeasure (X := fun _ => P) (Measure.dirac π₀) (fun n => homKernel κ n)

instance sosPathMeasure.instIsProbabilityMeasure
    (π₀ : P) (κ : Kernel P P) [IsMarkovKernel κ] :
    IsProbabilityMeasure (sosPathMeasure π₀ κ) := by
  unfold sosPathMeasure; infer_instance

end

/-! ## Stochastic Sacred Object System

A Stochastic SOS replaces the deterministic update δ : P → P with a
Markov kernel κ : Kernel P P.  The Monotone Improvement axiom becomes
stochastic: E[eval(κ(π, ·))] ≥ eval(π) — improvement in expectation.
The evaluator sequence n ↦ eval(ω(n)) then forms a submartingale,
and Doob's forward convergence theorem gives almost-sure convergence. -/

/-- A Stochastic Sacred Object System: a measurable state space with a
    bounded measurable evaluator and a Markov kernel transition satisfying
    stochastic monotone improvement. -/
structure StochasticSOS where
  /-- The state space -/
  P : Type*
  /-- Measurable structure on P -/
  [ms : MeasurableSpace P]
  /-- The evaluator function -/
  eval : P → ℝ
  /-- eval is measurable (needed for submartingale adaptedness) -/
  eval_measurable : Measurable eval
  /-- The Markov transition kernel -/
  kernel : Kernel P P
  /-- kernel is a Markov kernel (total mass 1 for every state) -/
  [markov : IsMarkovKernel kernel]
  /-- Stochastic monotone improvement: the expected evaluator value under one
      transition step is at least the current value.
      Replaces the deterministic axiom E(δ(π)) ≥ E(π). -/
  stoch_improvement : ∀ π : P, ∫ π', eval π' ∂(kernel π) ≥ eval π
  /-- Evaluator is uniformly bounded: |eval(π)| ≤ M for some M ≥ 0 and all π.
      Needed for L¹ integrability of the submartingale, which enables
      Doob's forward convergence theorem. -/
  eval_bound : ∃ M : ℝ≥0, ∀ π : P, |eval π| ≤ M

attribute [instance] StochasticSOS.ms StochasticSOS.markov

noncomputable section

/-- The evaluator process: at time n, evaluate the state ω(n).
    This is the stochastic analogue of the deterministic orbit
    n ↦ E(δ^[n](π₀)). -/
def StochasticSOS.evalProcess (S : StochasticSOS) (n : ℕ) (ω : ℕ → S.P) : ℝ :=
  S.eval (ω n)

/-! ## Submartingale Property

The evaluator process n ↦ eval(ω(n)) is a submartingale with respect to
the canonical filtration Filtration.piLE (generated by coordinates ≤ n)
and the path measure from Ionescu-Tulcea.  The three submartingale
conditions are:

1. **Strongly adapted**: eval(ω(n)) depends only on coordinate n, which is
   piLE(n)-measurable since n ≤ n.

2. **Conditional expectation inequality**: By the Markov property (condExp_traj),
   E[eval(ω(n+1)) | piLE(n)] = ∫ eval dκ(ω(n)) a.e., which is ≥ eval(ω(n))
   by stochastic improvement.

3. **Integrability**: eval is uniformly bounded, so each eval(ω(n)) is
   integrable w.r.t. any finite measure. -/

/-- **Adaptedness**: the evaluator process at time n depends only on
    coordinate n, which lies in piLE(n) since n ≤ n.
    Proof: evalProcess n factors through restrictLe n, hence is
    piLE(n)-measurable.  The factorisation is
    eval ∘ (π ↦ π ⟨n, le_refl⟩) ∘ restrictLe n. -/
theorem StochasticSOS.evalProcess_stronglyAdapted (S : StochasticSOS) (_π₀ : S.P) :
    StronglyAdapted (Filtration.piLE (X := fun _ => S.P)) S.evalProcess := by
  intro n
  -- evalProcess n factors as eval ∘ proj_{⟨n,_⟩} ∘ restrictLe n
  -- Each factor is measurable w.r.t. the appropriate σ-algebra:
  --   restrictLe n : (Π i, P, piLE n) → (Π j : Iic n, P, pi) by comap_measurable
  --   proj_{⟨n,_⟩} : (Π j : Iic n, P, pi) → (P, ms) by measurable_pi_apply
  --   eval : (P, ms) → (ℝ, borel) by eval_measurable
  exact (S.eval_measurable.comp
    ((measurable_pi_apply (⟨n, Set.mem_Iic.mpr le_rfl⟩ : ↥(Set.Iic n))).comp
     (comap_measurable (restrictLe (π := fun _ => S.P) n)))).stronglyMeasurable

/-- **Integrability**: the evaluator process is integrable because eval is
    uniformly bounded: |eval(π)| ≤ M implies ∫ |evalProcess n| dμ ≤ M < ∞. -/
theorem StochasticSOS.evalProcess_integrable (S : StochasticSOS) (π₀ : S.P) (n : ℕ) :
    Integrable (S.evalProcess n) (sosPathMeasure π₀ S.kernel) := by
  obtain ⟨M, hM⟩ := S.eval_bound
  exact Integrable.of_bound
    (S.eval_measurable.comp (measurable_pi_apply n)).aestronglyMeasurable M
    (Filter.Eventually.of_forall fun ω => by
      simp only [StochasticSOS.evalProcess, Real.norm_eq_abs]; exact hM (ω n))

/-- **Conditional expectation inequality**: by the Markov property
    (condExp_traj), the conditional expectation of evalProcess(n+1) given
    piLE(n) equals ∫ eval dκ(ω(n)) a.e.  The stochastic improvement axiom
    then gives ∫ eval dκ(ω(n)) ≥ eval(ω(n)) = evalProcess(n)(ω). -/
theorem StochasticSOS.evalProcess_condExp_le (S : StochasticSOS) (π₀ : S.P) (n : ℕ) :
    S.evalProcess n ≤ᵐ[sosPathMeasure π₀ S.kernel]
      (sosPathMeasure π₀ S.kernel)[S.evalProcess (n + 1) |
        Filtration.piLE (X := fun _ => S.P) n] := by
  -- Key identity: sosPathMeasure = traj (homKernel κ) 0 x₀
  -- where x₀ = piUnique⁻¹(π₀) wraps the initial state for Ionescu-Tulcea
  have hμ : sosPathMeasure π₀ S.kernel =
      Kernel.traj (X := fun _ => S.P) (fun m => homKernel S.kernel m) 0
        ((MeasurableEquiv.piUnique (fun _ : ↥(Finset.Iic 0) => S.P)).symm π₀) := by
    unfold sosPathMeasure Kernel.trajMeasure
    rw [Measure.map_dirac
      (MeasurableEquiv.piUnique (fun _ : ↥(Finset.Iic 0) => S.P)).symm.measurable]
    exact Measure.dirac_bind
      (Kernel.traj (X := fun _ => S.P) (fun m => homKernel S.kernel m) 0).measurable _
  rw [hμ]
  -- Integrability of evalProcess(n+1) under the traj measure
  have hint : Integrable (S.evalProcess (n + 1))
      (Kernel.traj (X := fun _ => S.P) (fun m => homKernel S.kernel m) 0
        ((MeasurableEquiv.piUnique (fun _ : ↥(Finset.Iic 0) => S.P)).symm π₀)) :=
    hμ ▸ S.evalProcess_integrable π₀ (n + 1)
  -- Apply the Markov property (condExp_traj): conditional expectation equals
  -- ∫ f d(traj κ n (frestrictLe n ω))
  filter_upwards [Kernel.condExp_traj (Nat.zero_le n) hint] with ω hω
  rw [hω]
  simp only [StochasticSOS.evalProcess]
  -- Goal: eval(ω n) ≤ ∫ y, eval(y(n+1)) d(traj κ n (frestrictLe n ω))
  -- Chain: ∫ eval(y(n+1)) dμ = ∫ eval d(μ.map proj_{n+1})  [integral_map]
  --        μ.map proj_{n+1} = (traj.map proj).app x = (κ n) x  [map_traj_succ_self]
  --        κ n x = homKernel n x = S.kernel(ω n)  [comap_apply, frestrictLe_apply]
  suffices h : ∫ y, S.eval (y (n + 1)) ∂Kernel.traj (X := fun _ => S.P)
      (fun m => homKernel S.kernel m) n (frestrictLe n ω) =
      ∫ z, S.eval z ∂S.kernel (ω n) by
    rw [h]; exact S.stoch_improvement (ω n)
  have hmeas : Measurable (fun (y : ℕ → S.P) => y (n + 1)) :=
    measurable_pi_apply (n + 1)
  -- Rewrite: ∫ eval(y(n+1)) dμ = ∫ eval d(μ.map proj_{n+1})
  rw [← integral_map hmeas.aemeasurable S.eval_measurable.aestronglyMeasurable]
  -- map_traj_succ_self: (traj κ).map proj_{n+1} = κ n
  -- then κ n = homKernel n, comap_apply, frestrictLe_apply give S.kernel(ω n)
  congr 1
  rw [← Kernel.map_apply _ hmeas, Kernel.map_traj_succ_self]
  simp only [homKernel, Kernel.comap_apply, frestrictLe_apply]

/-- The evaluator process is a submartingale w.r.t. the canonical filtration
    Filtration.piLE and the path measure constructed via Ionescu-Tulcea.
    Assembles from adaptedness, integrability, and the conditional expectation
    inequality (which uses condExp_traj + stochastic improvement). -/
theorem StochasticSOS.evalProcess_submartingale (S : StochasticSOS) (π₀ : S.P) :
    Submartingale S.evalProcess (Filtration.piLE (X := fun _ => S.P))
      (sosPathMeasure π₀ S.kernel) :=
  submartingale_nat
    (S.evalProcess_stronglyAdapted π₀)
    (S.evalProcess_integrable π₀)
    (S.evalProcess_condExp_le π₀)

/-! ## Almost-Sure Convergence (Doob's Theorem)

The main theorem: the evaluator sequence converges almost surely.
This is the stochastic analogue of the deterministic SOS convergence
theorem (which uses the Monotone Convergence Theorem on ℝ).  The proof
chain is: stochastic improvement → submartingale → L¹ bound → Doob. -/

/-- **Main Theorem**: Almost-sure convergence of the stochastic evaluator
    sequence.  For any Stochastic SOS and initial state π₀, the evaluator
    sequence n ↦ eval(ω(n)) converges almost surely under the path measure
    to a finite limit.

    Proof: The evaluator process is a bounded submartingale
    (evalProcess_submartingale), so Doob's forward convergence theorem
    (Submartingale.ae_tendsto_limitProcess) gives almost-sure convergence. -/
theorem StochasticSOS.convergence (S : StochasticSOS) (π₀ : S.P) :
    ∀ᵐ ω ∂(sosPathMeasure π₀ S.kernel),
      ∃ L : ℝ, Tendsto (fun n => S.eval (ω n)) atTop (nhds L) := by
  have hsub := S.evalProcess_submartingale π₀
  obtain ⟨M, hM⟩ := S.eval_bound
  -- The eLpNorm is bounded by M (probability measure, bounded function)
  have hbdd : ∀ n, eLpNorm (S.evalProcess n) 1 (sosPathMeasure π₀ S.kernel) ≤ M := by
    intro n
    have hae : ∀ᵐ ω ∂(sosPathMeasure π₀ S.kernel), ‖S.evalProcess n ω‖ ≤ (M : ℝ) :=
      Filter.Eventually.of_forall fun ω => by
        simp only [StochasticSOS.evalProcess, Real.norm_eq_abs]
        exact hM (ω n)
    calc eLpNorm (S.evalProcess n) 1 (sosPathMeasure π₀ S.kernel)
        ≤ (sosPathMeasure π₀ S.kernel) Set.univ ^ (1 : ℝ≥0∞).toReal⁻¹ *
          ENNReal.ofReal (M : ℝ) := eLpNorm_le_of_ae_bound hae
      _ = ENNReal.ofReal (M : ℝ) := by
          simp [measure_univ]
      _ = M := ENNReal.ofReal_coe_nnreal
  -- Doob's submartingale convergence theorem
  have hconv := hsub.ae_tendsto_limitProcess hbdd
  filter_upwards [hconv] with ω hω
  exact ⟨_, hω⟩

/-! ## Embedding: Deterministic SOS ↪ StochasticSOS

Every deterministic SOS embeds into StochasticSOS via the Dirac kernel
π ↦ δ_{δ(π)}.  The deterministic update δ : P → P becomes
Kernel.deterministic δ, and the stochastic improvement axiom reduces
to the deterministic monotone improvement axiom E(δ(π)) ≥ E(π),
since ∫ E dδ_{δ(π)} = E(δ(π)). -/

/-- Embed a deterministic SOS into StochasticSOS via the Dirac kernel.
    Requires measurability of E and δ (for the kernel construction) and
    a two-sided bound on E (for the L¹ condition).
    The stochastic improvement axiom reduces to the deterministic one. -/
def SOS.toStochasticSOS (S : SOS) [MeasurableSpace S.Pi] [MeasurableSingletonClass S.Pi]
    (hE_meas : Measurable S.E) (hδ_meas : Measurable S.delta)
    (hE_abs_bdd : ∃ M : ℝ≥0, ∀ π : S.Pi, |S.E π| ≤ M) : StochasticSOS where
  P := S.Pi
  eval := S.E
  eval_measurable := hE_meas
  kernel := Kernel.deterministic S.delta hδ_meas
  stoch_improvement := fun π => by
    rw [Kernel.integral_deterministic hδ_meas]
    exact S.monotone_improvement π
  eval_bound := hE_abs_bdd

/-- The embedding preserves the convergence guarantee: if a deterministic
    SOS satisfies the measurability and boundedness hypotheses, its
    stochastic embedding has almost-sure convergence (which for a
    deterministic system reduces to the original sure convergence). -/
theorem SOS.stochastic_convergence (S : SOS) [MeasurableSpace S.Pi] [MeasurableSingletonClass S.Pi]
    (hE_meas : Measurable S.E) (hδ_meas : Measurable S.delta)
    (hE_abs_bdd : ∃ M : ℝ≥0, ∀ π : S.Pi, |S.E π| ≤ M) (π₀ : S.Pi) :
    ∀ᵐ ω ∂(sosPathMeasure π₀ (Kernel.deterministic S.delta hδ_meas)),
      ∃ L : ℝ, Tendsto (fun n => S.E (ω n)) atTop (nhds L) :=
  (S.toStochasticSOS hE_meas hδ_meas hE_abs_bdd).convergence π₀

/-! ## Stochastic Morphisms

Structure-preserving maps between Stochastic SOS instances.  The
deterministic update commutativity f ∘ δ₁ = δ₂ ∘ f generalises to
kernel commutativity: pushing forward through f after a random step
in S₁ gives the same distribution as a random step in S₂ from f(π).

When both systems are deterministic (Dirac kernels), the kernel
commutativity condition reduces to the deterministic one. -/

/-- A morphism of Stochastic SOS instances: measurable maps (f, g)
    preserving evaluator compatibility and intertwining the Markov
    kernels via pushforward. -/
structure StochasticSOS.Morphism (S₁ S₂ : StochasticSOS) where
  /-- Map on state spaces -/
  f : S₁.P → S₂.P
  /-- Map on evaluator values -/
  g : ℝ → ℝ
  /-- f is measurable (needed for pushforward of kernel measures) -/
  f_measurable : Measurable f
  /-- g is monotone non-decreasing -/
  g_monotone : Monotone g
  /-- Evaluator compatibility: g ∘ eval₁ = eval₂ ∘ f -/
  evaluator_compat : ∀ π : S₁.P, g (S₁.eval π) = S₂.eval (f π)
  /-- Kernel commutativity: pushforward of κ₁(π) through f = κ₂(f(π)).
      Generalises deterministic update commutativity f ∘ δ₁ = δ₂ ∘ f. -/
  kernel_compat : ∀ π : S₁.P, (S₁.kernel π).map f = S₂.kernel (f π)

/-- Extensionality: two stochastic morphisms with the same underlying
    maps are equal (proof fields are propositions). -/
@[ext]
theorem StochasticSOS.Morphism.ext' {S₁ S₂ : StochasticSOS}
    {φ ψ : StochasticSOS.Morphism S₁ S₂}
    (hf : φ.f = ψ.f) (hg : φ.g = ψ.g) : φ = ψ := by
  cases φ; cases ψ; congr

/-- Identity morphism on a Stochastic SOS. -/
def StochasticSOS.Morphism.id (S : StochasticSOS) :
    StochasticSOS.Morphism S S where
  f := _root_.id
  g := _root_.id
  f_measurable := measurable_id
  g_monotone := monotone_id
  evaluator_compat := fun _ => rfl
  kernel_compat := fun _ => Measure.map_id

/-- Composition of stochastic morphisms.
    Kernel compatibility: (κ₁ π).map (f₂ ∘ f₁)
      = ((κ₁ π).map f₁).map f₂    [Measure.map_map]
      = (κ₂ (f₁ π)).map f₂        [φ₁.kernel_compat]
      = κ₃ (f₂ (f₁ π))            [φ₂.kernel_compat] -/
def StochasticSOS.Morphism.comp {S₁ S₂ S₃ : StochasticSOS}
    (φ₂ : StochasticSOS.Morphism S₂ S₃) (φ₁ : StochasticSOS.Morphism S₁ S₂) :
    StochasticSOS.Morphism S₁ S₃ where
  f := φ₂.f ∘ φ₁.f
  g := φ₂.g ∘ φ₁.g
  f_measurable := φ₂.f_measurable.comp φ₁.f_measurable
  g_monotone := φ₂.g_monotone.comp φ₁.g_monotone
  evaluator_compat := by
    intro π; simp only [Function.comp_apply]
    rw [φ₁.evaluator_compat, φ₂.evaluator_compat]
  kernel_compat := by
    intro π; simp only [Function.comp_apply]
    rw [← Measure.map_map φ₂.f_measurable φ₁.f_measurable,
        φ₁.kernel_compat, φ₂.kernel_compat]

/-- Left identity: id ∘ φ = φ. -/
theorem StochasticSOS.Morphism.id_comp {S₁ S₂ : StochasticSOS}
    (φ : StochasticSOS.Morphism S₁ S₂) :
    (StochasticSOS.Morphism.id S₂).comp φ = φ :=
  StochasticSOS.Morphism.ext' rfl rfl

/-- Right identity: φ ∘ id = φ. -/
theorem StochasticSOS.Morphism.comp_id {S₁ S₂ : StochasticSOS}
    (φ : StochasticSOS.Morphism S₁ S₂) :
    φ.comp (StochasticSOS.Morphism.id S₁) = φ :=
  StochasticSOS.Morphism.ext' rfl rfl

/-- Associativity: (φ₃ ∘ φ₂) ∘ φ₁ = φ₃ ∘ (φ₂ ∘ φ₁). -/
theorem StochasticSOS.Morphism.comp_assoc {S₁ S₂ S₃ S₄ : StochasticSOS}
    (φ₃ : StochasticSOS.Morphism S₃ S₄) (φ₂ : StochasticSOS.Morphism S₂ S₃)
    (φ₁ : StochasticSOS.Morphism S₁ S₂) :
    (φ₃.comp φ₂).comp φ₁ = φ₃.comp (φ₂.comp φ₁) :=
  StochasticSOS.Morphism.ext' rfl rfl

/-- The deterministic SOS embedding preserves morphisms:
    a deterministic SOS morphism induces a stochastic morphism between
    the embedded systems. -/
def SOS.Morphism.toStochasticMorphism {S₁ S₂ : SOS}
    [MeasurableSpace S₁.Pi] [MeasurableSingletonClass S₁.Pi]
    [MeasurableSpace S₂.Pi] [MeasurableSingletonClass S₂.Pi]
    (φ : SOS.Morphism S₁ S₂)
    (hE₁_meas : Measurable S₁.E) (hδ₁_meas : Measurable S₁.delta)
    (hE₁_bdd : ∃ M : ℝ≥0, ∀ π : S₁.Pi, |S₁.E π| ≤ M)
    (hE₂_meas : Measurable S₂.E) (hδ₂_meas : Measurable S₂.delta)
    (hE₂_bdd : ∃ M : ℝ≥0, ∀ π : S₂.Pi, |S₂.E π| ≤ M)
    (hf_meas : Measurable φ.f) : StochasticSOS.Morphism
      (S₁.toStochasticSOS hE₁_meas hδ₁_meas hE₁_bdd)
      (S₂.toStochasticSOS hE₂_meas hδ₂_meas hE₂_bdd) where
  f := φ.f
  g := φ.g
  f_measurable := hf_meas
  g_monotone := φ.g_monotone
  evaluator_compat := φ.evaluator_compat
  kernel_compat := fun π => by
    simp only [SOS.toStochasticSOS]
    rw [Kernel.deterministic_apply, Kernel.deterministic_apply,
        Measure.map_dirac hf_meas, φ.update_commute]

end
